### ISSUE TITLE
[Feature Request] Support list[-1] for array/slice like Python

### ISSUE THREAD

**Issue by JunGac** [antonmedv/expr#116]
In Python, negative numbers mean that you count from the right instead of the left. So, list[-1] refers to the last element, list[-2] is the second-last, and so on.

Do you have plan to support this feature in `expr`?

**Comment by antonmedv** [comment]
I was thinking a lot about this feature. It's really useful if you are coming from Python background, but it can confuse users who are not really into Python. For example, in golang you can't go it.  
And you required to write `list[len(list) - 1]` and this is good because it's explicit. Same thing for Expr. Features are good but should be added very carefully. Maybe you can give me more context on why do you think this is need feature?

**Comment by antonmedv** [comment]
So, for now, the desition is not to put in in core. 

But here is a solution using patcher: https://play.golang.org/p/1IBVAzKL2nz
```go
package main

import (
	"fmt"

	"github.com/antonmedv/expr"
	"github.com/antonmedv/expr/ast"
)

func main() {
	env := map[string]interface{}{
		"list": []int{1, 2, 3},
	}

	code := `list[-1]` // will output 3

	program, err := expr.Compile(code, expr.Env(env), expr.Patch(&patcher{}))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}
	fmt.Print(output)
}

type patcher struct{}

func (p *patcher) Enter(_ *ast.Node) {}
func (p *patcher) Exit(node *ast.Node) {
	n, ok := (*node).(*ast.IndexNode)
	if !ok {
		return
	}
	unary, ok := n.Index.(*ast.UnaryNode)
	if !ok {
		return
	}
	if unary.Operator == "-" {
		ast.Patch(&n.Index, &ast.BinaryNode{
			Operator: "-",
			Left:     &ast.BuiltinNode{Name: "len", Arguments: []ast.Node{n.Node}},
			Right:    unary.Node,
		})
	}

}
```
